### ISSUE TITLE
Support different datatypes

### ISSUE THREAD

**Issue by sanderd17** [POI-Importer/POI-Importer.github.io#6]
The tool should support different datatypes: ways and relations, as they can be used to mark areas.

**Comment by obtitus** [comment]
Hi, too lazy for a pull request, this at least gets some basic (optional!) support:

```
diff --git a/loadData.js b/loadData.js
index ca4d5a8..89b3bb3 100644
--- a/loadData.js
+++ b/loadData.js
@@ -144,13 +144,17 @@ function loadOverpass()
    var mapCenter = mapObj.getCenter();
    // Make query
    var query = "[out:json];\n";
-   var types = ["node"/*,"way","rel"*/];
+   
    var queriedDatasets = [];
    for (var datasetName in datasetSettings)
    {
        if (!tiledData[datasetName])
            continue;
-       var settings = datasetSettings[datasetName];
+           var settings = datasetSettings[datasetName];
+           var types = ["node"/*,"way","rel"*/];
+           if (typeof(settings.types) !== "undefined")
+           types = settings.types;
+
        var tileCoordinates = geoHelper.latlonToTilenumber(
            mapCenter.lat,
            mapCenter.lng,
```

**Comment by sanderd17** [comment]
@obtitus , did you test if this actually works with area types in OSM?

I tried to implement it, but I have never tested it.

**Comment by obtitus** [comment]
The "way" type seems to work fine. But I have yet to see the relation actually work. Not sure why... You can test it by looking at the kindergarten dataset, e.g. here:
http://poi-importer.github.io/#map=14/59.7225/10.8328&datasets=NOkg
if you enable the diff above, then you will get some matches. But only querying for "node" gives no matches, since there are no kindergartens mapped as nodes in this area.
